name: Package BepInEx mod

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo "{VERSION}={${GITHUB_REF/refs\/tags\//}}" >> $env:GITHUB_OUTPUT
#      - name: Build mod
#        id: build_mod
#        run: |
#        
#      - name: Zip package
#        id: zip
#        run: |
#          mkdir -p publish/plugins/MY_MOD_NAME
          
          